---
title: "Methods and Computing"
subtitle: "DoSS Summer Prep Bootcamp 2026"
output: 
  pdf_document:
    number_sections: true
    toc: false
fontsize: 11pt
geometry: margin=1in
header-includes:
  - \usepackage{booktabs}
  - \usepackage{array}
  - \usepackage{longtable}
  - \usepackage{caption}

---

# Time and Place

Exact times TBA

# Instructor 

Benjamin Smith [[benyamin.smith@mail.utoronto.ca](benyamin.smith@mail.utoronto.ca)]

# Course outline

This course will revisit foundational programming principles in `R` and review essential concepts in likelihood inference.

# Textbooks

## Primary Textbooks

- _All of Statistics_ by L. Wasserman (AoS)
- _Statistical Inference, Second Edition_ by George Casella and Robert L. Berger (C&B)

## Optional Texts

- _Statistical Models_ by A.C. Davison
- _Mathematical Statistics_ by K. Knight
- _Theory of Point Estimation_ by E.L. Lehmann

# Tentative Lecture Schedule

The Lecture Topcs and corresponding texts are outlined below. This schedule is tentative and may be changed as the course progresses. 

\newpage

| Module | Topics | References |
| :- | :--- | :--- |
| 1 | R, Rstudio, and Rmarkdown; Basic data types and structures | - |
| 2 | Reporting, data wrangling and graphing (I); LaTeX, `tidyverse` | - |
| 3 | Reporting, data wrangling and graphing (II); Elementary data analysis; `ggplot` and R style guide | - |
| 4 | Probability distributions; Statistical inference (I); Fundamental concepts in inference | AoS Chp 1-5; AoS Chp 6 |
| 5 | Statistical inference (II); Maximum likelihood estimation | C&B Chp 6.3, 7; AoS Chp 3-4 |
| 6 | Statistical inference (III); Hypothesis testing | AoS Chp 8; C&B Chap 8 |
| 7 | Statistical models (I); Linear regression models | AoS Chp 13; C&B Chp 11 |
| 8 | Statistical models (II); Generalized linear models | C&B Chp 12; AoS Chp 13 |
| 9 | Simulation and parallel computing | C&B Chap 10; AoS Chp 24 |
| 10 | Bootstrap | AoS Chp 5 |