---
title: "Methods and Computing"
description: "Instructor: Jianhui Gao, ([Email](mailto:jianhui.gao@mail.utoronto.ca))"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3

---

## Syllabus

[Click here to download the syllabus](Computing/2025/Syllabus.pdf) 

## Lectures

Lecture materials will be updated prior to the start of the lecture. There will be exercises for you to test your knowledge, and solutions will be provided after the lecture. If you have any questions, feel free to send me an email.

### Module 1: Basic R programming

- Slides: [pdf](Computing/2025/Slides/mod1.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex1.pdf), [Rmd](Computing/2025/Exercises/ex1.Rmd)

- Solutions: [pdf](Computing/2025/Solutions/sol1.pdf), [Rmd](Computing/2025/Solutions/sol1.Rmd)

- Recording: [Link](https://play.library.utoronto.ca/watch/dce3cab4acffac053266192e63141672)


### Module 2: Data wrangling (I)

LaTeX, tidyverse

- Slides: [pdf](Computing/2025/Slides/mod2.pdf)

- Data: [txt](Computing/2025/Slides/mtcars.txt)

- Exercises: [pdf](Computing/2025/Exercises/ex2.pdf), [Rmd](Computing/2025/Exercises/ex2.Rmd)

- Solutions: [pdf](Computing/2025/Solutions/sol2.pdf), [Rmd](Computing/2025/Solutions/sol2.Rmd)

- Recording: [Link](https://play.library.utoronto.ca/watch/3f6b0ac20d0ac47c721102f147fc76c3)



### Module 3: Data wrangling (II)

R style guide
- [Full Guide](https://style.tidyverse.org)

ggplot2

- Slides: [pdf](Computing/2025/Slides/mod3.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex3.pdf), [Rmd](Computing/2025/Exercises/ex3.Rmd)

- Data: [csv](Computing/2025/Exercises/Data/Bus_Breakdown_and_Delays.csv)

- Solutions: [pdf](Computing/2025/Solutions/sol3.pdf), [Rmd](Computing/2025/Solutions/sol3.Rmd)

- Recording: [Link](https://play.library.utoronto.ca/watch/1deb5821da55881e878a0198abd208f4)

 
### Module 4: Statistical inference (I)

Bias, Consistency, and MSE

- Slides: [pdf](Computing/2025/Slides/mod4.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex4.pdf), [Rmd](Computing/2025/Exercises/ex4.Rmd)

- Solutions: [pdf](Computing/2025/Solutions/sol4.pdf), [Rmd](Computing/2025/Solutions/sol4.Rmd)
 
- Recording：[Link](https://play.library.utoronto.ca/watch/7d208939c2ce265bc45edde98a08f942)

### Module 5: Statistical inference (II)

MLE, Numerical Methods

- Slides: [pdf](Computing/2025/Slides/mod5.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex5.pdf),
[Rmd](Computing/2025/Exercises/ex5.Rmd)

- Solutions: [pdf](Computing/2025/Solutions/sol5.pdf),
[Rmd](Computing/2025/Solutions/sol5.Rmd)

- Recording：[Link](https://play.library.utoronto.ca/watch/09a74130149f74927218e0d39d9b2e53)


### Module 6: Statistical inference (III)

Wald, Score, and Likelihood Ratio Test

- Slides: [pdf](Computing/2025/Slides/mod6.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex6.pdf), [Rmd](Computing/2025/Exercises/ex6.Rmd)

- Solutions: [pdf](Computing/2022/Solutions/sol6.pdf), [Rmd](Computing/2025/Solutions/sol6.Rmd)

<!-- - Recording：[Link](https://play.library.utoronto.ca/watch/47239f4d003313eddd2b843bff3a7760) -->


### Module 7: Linear regression 

- Slides: [pdf](Computing/2025/Slides/mod7.pdf) 

- Exercises: [pdf](Computing/2025/Exercises/ex7.pdf), [Rmd](Computing/2025/Exercises/ex7.Rmd)

- Solutions: [pdf](Computing/2025/Solutions/sol7.pdf), [Rmd](Computing/2025/Solutions/sol7.Rmd)

<!-- - Recording: [Link](https://play.library.utoronto.ca/watch/c886222f7d08bc3b40f628338eba617d) -->


### Module 8: Generalized linear models

<!-- - Slides: [pdf](Computing/2025/Slides/mod8.pdf)  -->

<!-- - Exercises: [pdf](Computing/2025/Exercises/ex8.pdf),  [Rmd](Computing/2025/Exercises/ex8.Rmd) -->

<!-- - Solution: [pdf](Computing/2025/Solutions/sol8.pdf), [Rmd](Computing/2025/Solutions/sol8.Rmd) -->

<!-- - Recording: [Link](https://play.library.utoronto.ca/watch/73637113a4d17d1cff9b83220a199050) -->



### Module 9: Parallel Computing in R


<!-- - Slides: [pdf](Computing/2025/Slides/mod9.pdf)  -->

<!-- - Exercises: [pdf](Computing/2025/Exercises/ex9.pdf) -->

<!-- - Solution: [pdf](Computing/2025/Solutions/sol9.pdf), [Rmd](Computing/2025/Solutions/sol9.Rmd) -->

<!-- - Recording: [Link](https://play.library.utoronto.ca/watch/a09e6bad7e19ec53fde95e3395dc44c4) -->



### Module 10: Bootstrap

<!-- - Slides: [pdf](Computing/2025/Slides/mod10.pdf)  -->

<!-- - Exercises: [pdf](Computing/2025/Exercises/ex10.pdf),  [Rmd](Computing/2025/Exercises/ex10.Rmd) -->

<!-- - Solution: [pdf](Computing/2025/Solutions/sol10.pdf), [Rmd](Computing/2025/Solutions/sol10.Rmd) -->

<!-- - Recording: [Link](https://play.library.utoronto.ca/watch/b34a2c5d17a5c70f0f1524a748b745b5) -->
