---
title: "Methods and Computing"
description: "Instructor: Yuan Tian ([Email](mailto:yuant.tian@mail.utoronto.ca)); Jianhui Gao ([Email](mailto:jianhui.gao@mail.utoronto.ca))"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3

---

## Syllabus

[Click here to download the syllabus](Computing/2023/syllabus_computing.pdf)



## Lectures



### Module 1: Basic R programming

- Slides: [pdf](Computing/2023/Slides/mod1.pdf) 

- Exercises: [pdf](Computing/2023/Exercises/ex1.pdf), [Rmd](Computing/2022/Exercises/ex1.Rmd)

- Solutions: [pdf](Computing/2023/Solutions/sol1.pdf), [Rmd](Computing/2022/Solutions/sol1.Rmd)



### Module 2: Data wrangling (I)

LaTeX, tidyverse

- Slides: [pdf](Computing/2023/Slides/mod2.pdf) 

- Exercises: [pdf](Computing/2023/Exercises/ex2.pdf), [Rmd](Computing/2023/Exercises/ex2.Rmd)

- Solutions: [pdf](Computing/2023/Solutions/sol2.pdf), [Rmd](Computing/2023/Solutions/sol2.Rmd)



### Module 3: Data wrangling (II)

R style guide
- [Full Guide](https://style.tidyverse.org)

ggplot2

- Tutorial: [pdf](Computing/2023/Slides/ggplot2_tutorial.pdf), [Rmd](Computing/2023/Slides/ggplot2_tutorial.Rmd)

- Exercises: [pdf](Computing/2022/Exercises/ex3.pdf), [Rmd](Computing/2022/Exercises/ex3.Rmd)

- Solutions: [pdf](Computing/2022/Solutions/sol3.pdf), [Rmd](Computing/2022/Solutions/sol3.Rmd)

 
### Module 4: Statistical inference (I)

Bias, Consistency, and MSE

- Slides: [pdf](Computing/2023/Slides/mod4.pdf) 

- Exercises: [pdf](Computing/2022/Exercises/ex4.pdf), [Rmd](Computing/2022/Exercises/ex4.Rmd)

- Solutions: [pdf](Computing/2022/Solutions/sol4.pdf), [Rmd](Computing/2022/Solutions/sol4.Rmd)


### Module 5: Statistical inference (II)

MLE, Numerical Methods

- Slides: [pdf](Computing/2023/Slides/mod5.pdf) 

- Exercises: [pdf](Computing/2022/Exercises/ex5.pdf)

- Solutions: [pdf](Computing/2022/Solutions/sol5.pdf), [Rmd](Computing/2022/Solutions/sol5.Rmd)



### Module 6: Statistical inference (III)
Wald, Score, and Likelihood Ratio Test

- Slides: [pdf](Computing/2023/Slides/mod6.pdf) 

- Exercises: [pdf](Computing/2022/Exercises/ex6.pdf)

- Solutions: [pdf](Computing/2022/Solutions/sol6.pdf)



### Module 7: Linear regression 

- Slides: [pdf](Computing/2023/Slides/mod7.pdf) 

- Exercises: [pdf](Computing/2023/Exercises/ex7.pdf)

- Solutions: [pdf](Computing/2023/Solutions/sol7.pdf), [Rmd](Computing/2023/Solutions/sol7.Rmd)



### Module 8: Generalized linear models

- Slides: [pdf](Computing/2023/Slides/mod8.pdf) 

- Exercises: [pdf](Computing/2023/Exercises/ex8.pdf)

- Solution: [pdf](Computing/2023/Solutions/sol8.pdf), [Rmd](Computing/2023/Solutions/sol8.Rmd)


<!-- 
### Module 9: Linear regression

- Slides: [pdf](Computing/2022/Slides/mod9.pdf) 

- Exercises: [pdf](Computing/2022/Exercises/ex9.pdf)

- Solution: [pdf](Computing/2022/Solutions/sol9.pdf), [Rmd](Computing/2022/Solutions/sol9.Rmd)
-->

<!-- 
### Module 10: Generalized linear models

- Slides: [pdf](Computing/2022/Slides/mod10.pdf) 

- Exercises: [pdf](Computing/2022/Exercises/ex10.pdf)

- Solution: [pdf](Computing/2022/Solutions/sol10.pdf), [Rmd](Computing/2022/Solutions/sol10.Rmd)
-->