---
title: "Summer Prep Bootcamp 2025"
description: 
output:
  distill::distill_article:
    toc: true
    toc_depth: 3

---

The DoSS Summer Prep Bootcamp 2025 was held from July 7 to July 25 2025. 

## Methods and Computing
Instructor: Jianhui Gao, PhD student ([Email](mailto:jianhui.gao@mail.utoronto.ca))

### Syllabus

[Click here to download the syllabus](Computing/2025/Syllabus.pdf) 


### Lectures

Lecture materials will be updated prior to the start of the lecture. There will be exercises for you to test your knowledge, and solutions will be provided after the lecture. If you have any questions, feel free to send me an email.

#### Module 1: Basic R programming

- Slides: [pdf](Computing/2025/Slides/mod1.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex1.pdf), [Rmd](Computing/2025/Exercises/ex1.Rmd)

- Solutions: [pdf](Computing/2025/Solutions/sol1.pdf), [Rmd](Computing/2025/Solutions/sol1.Rmd)


#### Module 2: Data wrangling (I)

LaTeX, tidyverse

- Slides: [pdf](Computing/2025/Slides/mod2.pdf)

- Data: [txt](Computing/2025/Slides/mtcars.txt)

- Exercises: [pdf](Computing/2025/Exercises/ex2.pdf), [Rmd](Computing/2025/Exercises/ex2.Rmd)

- Solutions: [pdf](Computing/2025/Solutions/sol2.pdf), [Rmd](Computing/2025/Solutions/sol2.Rmd)



#### Module 3: Data wrangling (II)

R style guide
- [Full Guide](https://style.tidyverse.org)

ggplot2

- Slides: [pdf](Computing/2025/Slides/mod3.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex3.pdf), [Rmd](Computing/2025/Exercises/ex3.Rmd)

- Data: [csv](Computing/2025/Exercises/Data/Bus_Breakdown_and_Delays.csv)

- Solutions: [pdf](Computing/2025/Solutions/sol3.pdf), [Rmd](Computing/2025/Solutions/sol3.Rmd)


 
#### Module 4: Statistical inference (I)

Bias, Consistency, and MSE

- Slides: [pdf](Computing/2025/Slides/mod4.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex4.pdf), [Rmd](Computing/2025/Exercises/ex4.Rmd)

- Solutions: [pdf](Computing/2025/Solutions/sol4.pdf), [Rmd](Computing/2025/Solutions/sol4.Rmd)
 

#### Module 5: Statistical inference (II)

MLE, Numerical Methods

- Slides: [pdf](Computing/2025/Slides/mod5.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex5.pdf),
[Rmd](Computing/2025/Exercises/ex5.Rmd)

- Solutions: [pdf](Computing/2025/Solutions/sol5.pdf),
[Rmd](Computing/2025/Solutions/sol5.Rmd)




#### Module 6: Statistical inference (III)

Wald, Score, and Likelihood Ratio Test

- Slides: [pdf](Computing/2025/Slides/mod6.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex6.pdf), [Rmd](Computing/2025/Exercises/ex6.Rmd)

- Solutions: [pdf](Computing/2022/Solutions/sol6.pdf), [Rmd](Computing/2025/Solutions/sol6.Rmd)



#### Module 7: Linear regression 

- Slides: [pdf](Computing/2025/Slides/mod7.pdf) 

- Exercises: [pdf](Computing/2025/Exercises/ex7.pdf), [Rmd](Computing/2025/Exercises/ex7.Rmd)

- Solutions: [pdf](Computing/2025/Solutions/sol7.pdf), [Rmd](Computing/2025/Solutions/sol7.Rmd)




#### Module 8: Generalized linear models

- Slides: [pdf](Computing/2025/Slides/mod8.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex8.pdf),  [Rmd](Computing/2025/Exercises/ex8.Rmd)

- Solution: [pdf](Computing/2025/Solutions/sol8.pdf), [Rmd](Computing/2025/Solutions/sol8.Rmd)





#### Module 9: Parallel Computing in R


- Slides: [pdf](Computing/2025/Slides/mod9.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex9.pdf), [Rmd](Computing/2025/Exercises/ex9.Rmd)

- Solution: [pdf](Computing/2025/Solutions/sol9.pdf), [Rmd](Computing/2025/Solutions/sol9.Rmd)




#### Module 10: Bootstrap

- Slides: [pdf](Computing/2025/Slides/mod10.pdf)

- Exercises: [pdf](Computing/2025/Exercises/ex10.pdf),  [Rmd](Computing/2025/Exercises/ex10.Rmd)

- Solution: [pdf](Computing/2025/Solutions/sol10.pdf), [Rmd](Computing/2025/Solutions/sol10.Rmd)



## Operational Math
Instructor: [Ichiro Hashimoto](https://ichiro-h.github.io/), PhD student

### Syllabus
[Click here to download the syllabus](Math/2025/syllabus/syllabus_operational_math.pdf)


### Lectures

You may download the [lecture notes](Math/2025/lecture_notes/math_notes.pdf), which will be updated after each lecture.

#### Module 1: Introduction to proofs

 - Slides: [fillable](Math/2025/module1/slides.pdf),   [filled](Math/2025/module1/slides_filled.pdf)

 - Exercises: [pdf](Math/2025/module1/exercises.pdf), [LaTeX template](Math/2025/module1/exercises.tex),  [solutions](Math/2025/module1/exercise_solutions.pdf) 



#### Module 2: Set theory I

- Slides: [fillable](Math/2025/module2/slides.pdf),  [filled](Math/2025/module2/slides_filled.pdf)

- Exercises: [pdf](Math/2025/module2/exercises.pdf), [LaTeX template](Math/2025/module2/exercises.tex), 
[solutions](Math/2025/module2/exercise_solutions.pdf)


#### Module 3: Set theory II and metric spaces I
 - Slides: [fillable](Math/2025/module3/slides.pdf), [filled](Math/2025/module3/slides_filled.pdf)

- Exercises: [pdf](Math/2025/module3/exercises.pdf), [LaTeX template](Math/2025/module3/exercises.tex) ,  [solutions](Math/2025/module3/exercise_solutions.pdf)



#### Module 4: Metric spaces II

 - Slides: [fillable](Math/2025/module4/slides.pdf),  [filled](Math/2025/module4/slides_filled.pdf) -->

 - Exercises: [pdf](Math/2025/module4/exercises.pdf), [LaTeX template](Math/2025/module4/exercises.tex), [solutions](Math/2025/module4/exercise_solutions.pdf)


#### Module 5: Metric spaces III

- Slides: [fillable](Math/2025/module5/slides.pdf),  [filled](Math/2025/module5/slides_filled.pdf)

 - Exercises: [pdf](Math/2025/module5/exercises.pdf), [LaTeX](Math/2025/module5/exercises.tex),  [solutions](Math/2025/module5/exercise_solutions.pdf)


#### Module 6: Metric spaces IV

 - Slides: [fillable](Math/2025/module6/slides.pdf) , [filled](Math/2025/module6/slides_filled.pdf)

- Exercises: [pdf](Math/2025/module6/exercises.pdf), [LaTeX](Math/2025/module6/exercises.tex),  [solutions](Math/2025/module6/exercise_solutions.pdf) 
 


#### Module 7: Linear algebra I

- Slides: [fillable](Math/2025/module7/slides.pdf),  [filled](Math/2025/module7/slides_filled.pdf) 

- Exercises: [pdf](Math/2025/module7/exercises.pdf), [LaTeX](Math/2025/module7/exercises.tex),  [solutions](Math/2025/module7/exercise_solutions.pdf)


#### Module 8: Linear algebra II

- Slides: [fillable](Math/2025/module8/slides.pdf),  [filled](Math/2025/module8/slides_filled.pdf)

 - Exercises: [pdf](Math/2025/module8/exercises.pdf), [LaTeX](Math/2025/module8/exercises.tex),  [solutions](Math/2025/module8/exercise_solutions.pdf)



#### Module 9: Linear algebra III

- Slides: [fillable](Math/2025/module9/slides.pdf),  [filled](Math/2025/module9/slides_filled.pdf) 

 - Exercises: [pdf](Math/2025/module9/exercises.pdf), [LaTeX](Math/2025/module9/exercises.tex),  [solutions](Math/2025/module9/exercise_solutions.pdf) 



#### Module 10: Differentiation and integration

- Slides: [fillable](Math/2025/module10/slides.pdf), 
 [filled](Math/2025/module10/slides_filled.pdf) 

 - Exercises: [pdf](Math/2025/module10/exercises.pdf), [LaTeX](Math/2025/module10/exercises.tex),
 [solutions](Math/2025/module10/exercise_solutions.pdf) 



## Probability
Instructor: [Ichiro Hashimoto](https://ichiro-h.github.io/), PhD student (2nd Year)

### Syllabus

[Click here to download the syllabus](Probability/2025/Syllabus/Bootcamp_Probability_Syllabus.pdf)


### Lectures


#### Module 1: Basics of Probability
- Slides: [Module 1](Probability/2025/Slides/Module_1.pdf); [Module 1 Annotated](Probability/2025/Slides/Module_1_annotated.pdf)  

 - Problem Set Solutions: [Module 1 Solution](Probability/2025/Solutions/Module_1_Solutions.pdf)  



#### Module 2: Random Variables
- Slides: [Module 2](Probability/2025/Slides/Module_2.pdf);  [Module 2 Annotated](Probability/2025/Slides/Module_2_annotated.pdf)  

 - Problem Set Solutions: [Module 2 Solution](Probability/2025/Solutions/Module_2_Solutions.pdf)  



#### Mule 3: Common Random Variables

- Slides: [Module 3](Probability/2025/Slides/Module_3.pdf);  [Module 3 Annotated](Probability/2025/Slides/Module_3_annotated.pdf)  

- Problem Set Solutions: [Module 3 Solution](Probability/2025/Solutions/Module_3_Solutions.pdf)



#### Mule 4: Distribution

 - Slides: [Module 4](Probability/2025/Slides/Module_4.pdf); [Module 4 Annotated](Probability/2025/Slides/Module_4_annotated.pdf)  

 - Problem Set Solutions: [Module 4 Solution](Probability/2025/Solutions/Module_4_Solutions.pdf)  



#### Mule 5: Expectation

- Slides: [Module 5](Probability/2025/Slides/Module_5.pdf);  [Module 5 Annotated](Probability/2025/Slides/Module_5_annotated.pdf)  

- Problem Set Solutions: [Module 5 Solution](Probability/2025/Solutions/Module_5_Solutions.pdf) 


#### Mule 6: Inequalities

- Slides: [Module 6](Probability/2025/Slides/Module_6.pdf); 
[Module 6 Annotated](Probability/2025/Slides/Module_6_annotated.pdf)

- Problem Set Solutions: [Module 6 Solution](Probability/2025/Solutions/Module_6_Solutions.pdf)



#### Mule 7: Stochastic Convergence


- Slides: [Module 7](Probability/2025/Slides/Module_7.pdf); 
[Module 7 Annotated](Probability/2025/Slides/Module_7_annotated.pdf)

- Problem Set Solutions: [Module 7 Solution](Probability/2025/Solutions/Module_7_Solutions.pdf)



#### Mule 8: Limit Theorems

- Slides: [Module 8](Probability/2025/Slides/Module_8.pdf); 
 [Module 8 Annotated](Probability/2025/Slides/Module_8_annotated.pdf) 



#### Mule 9 - 10: Counterexamples

- Slides: [Module 9- 10](Probability/2025/Slides/Module_9.pdf); 
 [Module 9 Annotated](Probability/2025/Slides/Module_9_annotated.pdf) 
