---
title: "Operational Math"
description: "Instructor: [Huanlin Mao](mailto:hl.mao@mail.utoronto.ca), PhD student"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3

---

## Syllabus
[Click here to download the syllabus](Math/2026/syllabus/syllabus_operational_math.pdf)


## Lectures

Material will be added here as the course progresses. I will add slides and exercises before the lecture. After the lecture, I will add the annotated slides and update the lecture notes. 


Note: I will comment these in as the course progresses. Before each lecture students will have access to the slides with blanks as well as the exercises (either a pdf or a tex file they can fill in). After each lecture I will add the filled-in slides (I will hand-write during the lecture) and update the lecture notes


You may download the [lecture notes](Math/2026/lecture_notes/math_notes.pdf), which will be updated after each lecture.



### Module 1: Introduction to proofs

Slides:   [fillable](Math/2026/module1/slides.pdf), [filled](Math/2026/module1/slides_filled.pdf)

Exercises: [pdf](Math/2026/module1/exercises.pdf), [LaTeX template](Math/2026/module1/exercises.tex),  [solutions](Math/2026/module1/exercise_solutions.pdf)

Recordings: [link](https://play.library.utoronto.ca/watch/69ec83231d0b55725a57fb156b1a99fd)

### Module 2: Set theory I

Slides: [fillable](Math/2026/module2/slides.pdf), [filled](Math/2026/module2/slides_filled.pdf)

Exercises: [pdf](Math/2026/module2/exercises.pdf), [LaTeX template](Math/2026/module2/exercises.tex), [solutions](Math/2026/module2/exercise_solutions.pdf)

Recordings: [link](https://play.library.utoronto.ca/watch/a1bd1a57f68e20686346a22733626f42)


### Module 3: Set theory II and metric spaces I

Slides: [fillable](Math/2026/module3/slides.pdf), [filled](Math/2026/module3/slides_filled.pdf)

Exercises: [pdf](Math/2026/module3/exercises.pdf), [LaTeX template](Math/2026/module3/exercises.tex) ,  [solutions](Math/2026/module3/exercise_solutions.pdf)

Recordings: [link](https://play.library.utoronto.ca/watch/c997dbae9a35d141b71deb7dbd63eedf)

### Module 4: Metric spaces II

Slides: [fillable](Math/2026/module4/slides.pdf),  [filled](Math/2026/module4/slides_filled.pdf)

Exercises: [pdf](Math/2026/module4/exercises.pdf), [LaTeX template](Math/2026/module4/exercises.tex), [solutions](Math/2026/module4/exercise_solutions.pdf)

Recordings: [link](https://play.library.utoronto.ca/watch/1b370072ddf1d7e88ed274a5adcd835a)


### Module 5: Metric spaces III

Slides: [fillable](Math/2026/module5/slides.pdf),  [filled](Math/2026/module5/slides_filled.pdf)

Exercises: [pdf](Math/2026/module5/exercises.pdf), [LaTeX](Math/2026/module5/exercises.tex),  [solutions](Math/2026/module5/exercise_solutions.pdf)

Recordings: [link](https://play.library.utoronto.ca/watch/bb0ee780f4f6dee2b6102c185fa1cdc9)

### Module 6: Metric spaces IV

Slides: [fillable](Math/2026/module6/slides.pdf) , [filled](Math/2026/module6/slides_filled.pdf)

Exercises: [pdf](Math/2026/module6/exercises.pdf), [LaTeX](Math/2026/module6/exercises.tex),  [solutions](Math/2026/module6/exercise_solutions.pdf)

Recordings: [link](https://play.library.utoronto.ca/watch/bfaf3b0039408e0f3161af75ab86747f)

### Module 7: Linear algebra I

Slides: [fillable](Math/2026/module7/slides.pdf)

Exercises: [pdf](Math/2026/module7/exercises.pdf), [LaTeX](Math/2026/module7/exercises.tex)

<!-- - Slides: [fillable](Math/2026/module7/slides.pdf),  [filled](Math/2026/module7/slides_filled.pdf)  -->

<!-- - Exercises: [pdf](Math/2026/module7/exercises.pdf), [LaTeX](Math/2026/module7/exercises.tex),  [solutions](Math/2026/module7/exercise_solutions.pdf) -->

<!-- - Recordings: [link](https://play.library.utoronto.ca/watch/07cb585709869911598a3ea34977f425) -->

### Module 8: Linear algebra II

<!-- - Slides: [fillable](Math/2026/module8/slides.pdf),  [filled](Math/2026/module8/slides_filled.pdf) -->

<!--  - Exercises: [pdf](Math/2026/module8/exercises.pdf), [LaTeX](Math/2026/module8/exercises.tex),  [solutions](Math/2026/module8/exercise_solutions.pdf) -->

<!-- - Recordings: [link](https://play.library.utoronto.ca/watch/ebf7e655e861fc1f2c4a3a1f0ab67e23) -->

### Module 9: Linear algebra III

<!-- - Slides: [fillable](Math/2026/module9/slides.pdf),  [filled](Math/2026/module9/slides_filled.pdf)  -->

<!--  - Exercises: [pdf](Math/2026/module9/exercises.pdf), [LaTeX](Math/2026/module9/exercises.tex),  [solutions](Math/2026/module9/exercise_solutions.pdf)  -->

<!-- - Recordings: [link](https://play.library.utoronto.ca/watch/bea2fcc02328ba8fc5b460fd0ac47fc7) -->

### Module 10: Differentiation and integration

<!-- - Slides: [fillable](Math/2026/module10/slides.pdf),  -->
<!--  [filled](Math/2026/module10/slides_filled.pdf)  -->

<!--  - Exercises: [pdf](Math/2026/module10/exercises.pdf), [LaTeX](Math/2026/module10/exercises.tex), -->
<!--  [solutions](Math/2026/module10/exercise_solutions.pdf)  -->

<!--  - Recordings: [link](https://play.library.utoronto.ca/watch/bd1a9b6d865b224b4dee53aedcdccdf6)  -->
