---
title: "Methods and Computing"
author: "Instructor: [Siyue Yang](https://siyueyang.github.io)"
output:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: true
    theme: yeti
  # pdf_document:
  #   toc: yes
  #   toc_depth: '4'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F, message = F)
```

---

<br>

## Syllabus

[Click here to download the syllabus](Computing/syllabus_computing.pdf)

<br>

## Lectures

Material will be added here as the course progresses.

<br>

### Module 1: Basic programming in R

- Slides: [pdf](Computing/Slides/mod1.pdf) 

- Exercises: [pdf](Computing/Exercises/ex1.pdf), [Rmd](Computing/Exercises/ex1.Rmd)

- Solutions: [pdf](Computing/Solutions/sol1.pdf), [Rmd](Computing/Solutions/sol1.Rmd)

<br>

### Module 2: Reporting, data Wrangling and graphing (I)

LaTeX, Markdown, tidyverse

- Slides: [pdf](Computing/Slides/mod2.pdf) 

- Exercises: [pdf](Computing/Exercises/ex2.pdf), [Rmd](Computing/Exercises/ex2.Rmd)

- Solutions: [pdf](Computing/Solutions/sol2.pdf), [Rmd](Computing/Solutions/sol2.Rmd)

<br>

### Module 3: Reporting, data Wrangling and graphing (II)

ggplot2

- Slides: [pdf](Computing/Slides/mod3.pdf) 

- Exercises: [pdf](Computing/Exercises/ex3.pdf), [Rmd](Computing/Exercises/ex3.Rmd)

- Solutions: [pdf](Computing/Solutions/sol3.pdf), [Rmd](Computing/Solutions/sol3.Rmd)

<br>

### Module 4: Statistical inference (I)

Probability distributions

- Slides: [pdf](Computing/Slides/mod4.pdf) 

- Exercises: [pdf](Computing/Exercises/ex4.pdf), [Rmd](Computing/Exercises/ex4.Rmd)

- Solutions: [pdf](Computing/Solutions/sol4.pdf), [Rmd](Computing/Solutions/sol4.Rmd)

<br>

### Module 5: Statistical inference (II)

Estimation

- Slides: [pdf](Computing/Slides/mod5.pdf) 

- Exercises: [pdf](Computing/Exercises/ex5.pdf)

- Solutions: [pdf](Computing/Solutions/sol5.pdf), [Rmd](Computing/Solutions/sol5.Rmd)

<br>

### Module 6: Statistical inference (III)
Hypothesis testing

- Slides: [pdf](Computing/Slides/mod6.pdf) 

- Exercises: [pdf](Computing/Exercises/ex6.pdf)

- Solutions: [pdf](Computing/Solutions/sol6.pdf)

<br>

### Module 7: Simulations 

- Slides: [pdf](Computing/Slides/mod7.pdf) 

- Exercises: [pdf](Computing/Exercises/ex7.pdf)

- Solutions: [pdf](Computing/Solutions/sol7.pdf), [Rmd](Computing/Solutions/sol7.Rmd)

<br>

### Module 8: Bootstrap

- Slides: [pdf](Computing/Slides/mod8.pdf) 

- Exercises: [pdf](Computing/Exercises/ex8.pdf)

- Solution: [pdf](Computing/Solutions/sol8.pdf), [Rmd](Computing/Solutions/sol8.Rmd)

<br>

### Module 9: Linear regression

- Slides: [pdf](Computing/Slides/mod9.pdf) 

- Exercises: [pdf](Computing/Exercises/ex9.pdf)

- Solution: [pdf](Computing/Solutions/sol9.pdf), [Rmd](Computing/Solutions/sol9.Rmd)

<br>

### Module 10: Generalized linear regression


<!-- ### Bootstrap -->

<!-- - <a href="https://github.com/jlgrons/UofT-DoSS-SPB/blob/main/Computing/Slides/mod8.pdf"target="_blank">Slides</a> -->


<!-- <br> -->

<!-- ### Regression -->

<!-- <br> -->




