---
title: 'Operational Math'
author: "Instructor: [Emma Kroell](https://www.emmakroell.ca)"
output: 
  html_document:
   toc: true
   toc_float: true
   theme: yeti
---

---

<br>

## Syllabus

[Click here to download the syllabus](Math/syllabus/syllabus_operational_math.pdf)

<br>

## Lectures

Material will be added here as the course progresses. I will add slides and exercises before the lecture. After the lecture, I will add the annotated slides and update the lecture notes. 

<!-- Note: I will comment these in as the course progresses. Before each lecture students will have access to the slides with blanks as well as the exercises (either a pdf or a tex file they can fill in). After each lecture I will add the filled-in slides (I will hand-write during the lecture) and update the lecture notes -->


You may download the [lecture notes](Math/lecture_notes/math_notes.pdf), which will be updated after each lecture.

<br>

### Module 1: Introduction to proofs

- Slides: [fillable](Math/module1/slides.pdf),  [filled](Math/module1/slides_filled.pdf)

- Exercises: [pdf](Math/module1/exercises.pdf), [LaTeX template](Math/module1/exercises.tex), [solutions](Math/module1/exercise_solutions.pdf)


<br>

### Module 2: Set theory

- Slides: [fillable](Math/module2/slides.pdf), [filled](Math/module2/slides_filled.pdf)

- Exercises: [pdf](Math/module2/exercises.pdf), [LaTeX template](Math/module2/exercises.tex), [solutions](Math/module2/exercise_solutions.pdf)


<br>

### Module 3: Set theory II and metric spaces I

- Slides: [fillable](Math/module3/slides.pdf), [filled](Math/module3/slides_filled.pdf)

- Exercises: [pdf](Math/module3/exercises.pdf), [LaTeX template](Math/module3/exercises.tex), [solutions](Math/module3/exercise_solutions.pdf)


<br>

### Module 4: Metric spaces II

- Slides: [fillable](Math/module4/slides.pdf), [filled](Math/module4/slides_filled.pdf)

- Exercises: [pdf](Math/module4/exercises.pdf), [LaTeX template](Math/module4/exercises.tex), [solutions](Math/module4/exercise_solutions.pdf)


<br>

### Module 5: Metric spaces III and Topology I

- Slides: [fillable](Math/module5/slides.pdf), [filled](Math/module5/slides_filled.pdf)

- Exercises: [pdf](Math/module5/exercises.pdf), [LaTeX](Math/module5/exercises.tex), [solutions](Math/module5/exercise_solutions.pdf) 

<br>

### Module 6: Topology II and intro to linear algebra

- Slides: [fillable](Math/module6/slides.pdf), [filled](Math/module6/slides_filled.pdf)

- Exercises: [pdf](Math/module6/exercises.pdf), [LaTeX](Math/module6/exercises.tex), [solutions](Math/module6/exercise_solutions.pdf) 


<br>

### Module 7: Linear algebra I

- Slides: [fillable](Math/module7/slides.pdf), [filled](Math/module7/slides_filled.pdf)

- Exercises: [pdf](Math/module7/exercises.pdf), [LaTeX](Math/module7/exercises.tex), [solutions](Math/module7/exercise_solutions.pdf)


<br>

### Module 8: Linear algebra II

- Slides: [fillable](Math/module8/slides.pdf), [filled](Math/module8/slides_filled.pdf)

- Exercises: [pdf](Math/module8/exercises.pdf), [LaTeX](Math/module8/exercises.tex), [solutions](Math/module8/exercise_solutions.pdf)



<br>

### Module 9: Linear algebra III

- Slides: [fillable](Math/module9/slides.pdf), [filled](Math/module9/slides_filled.pdf)

- Exercises: [pdf](Math/module9/exercises.pdf), [LaTeX](Math/module9/exercises.tex), [solutions](Math/module9/exercise_solutions.pdf)


<br>

### Module 10: Differentiation and integration

- Slides: [fillable](Math/module10/slides.pdf), [filled](Math/module10/slides_filled.pdf)

- Exercises: [pdf](Math/module10/exercises.pdf), [LaTeX](Math/module10/exercises.tex), [solutions](Math/module10/exercise_solutions.pdf)






