---
title: "Probability"
description: "Instructor: [Ichiro Hashimoto](https://ichiro-h.github.io/), PhD student"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3

---


## Syllabus

[Click here to download the syllabus](Probability/2026/Syllabus/Bootcamp_Probability_Syllabus.pdf)


## Lectures

Material will be added here as the course progresses.


### Module 1: Basics of Probability
- Slides: [Module 1](Probability/2026/Slides/Module_1.pdf); [Module 1 Annotated](Probability/2026/Slides/Module_1_annotated.pdf)

- Problem Set Solutions: [Module 1 Solution](Probability/2026/Solutions/Module_1_Solutions.pdf) 

- Recordings: [Link](https://play.library.utoronto.ca/watch/90750b0e69a4002f03a0f67a8f7dd895)

### Module 2: Random Variables
- Slides: [Module 2](Probability/2026/Slides/Module_2.pdf); [Module 2 Annotated](Probability/2026/Slides/Module_2_annotated.pdf)

- Problem Set Solutions: [Module 2 Solution](Probability/2026/Solutions/Module_2_Solutions.pdf)

- Recordings: [Link](https://play.library.utoronto.ca/watch/174ac7e0512fe7c0ecfaa73a237e117b)

### Module 3: Common Random Variables

- Slides: [Module 3](Probability/2026/Slides/Module_3.pdf); [Module 3 Annotated](Probability/2026/Slides/Module_3_annotated.pdf)  

- Problem Set Solutions: [Module 3 Solution](Probability/2026/Solutions/Module_3_Solutions.pdf)

- Recordings: [link](https://play.library.utoronto.ca/watch/b6283f7d3bbceeac6fbf007b182ba2ab)

### Module 4: Distribution

- Slides: [Module 4](Probability/2026/Slides/Module_4.pdf); [Module 4 Annotated](Probability/2026/Slides/Module_4_annotated.pdf)

- Problem Set Solutions: [Module 4 Solution](Probability/2026/Solutions/Module_4_Solutions.pdf) 

- Recordings: [link](https://play.library.utoronto.ca/watch/d4c456bd6c7078cb7c6ed8040d34397e)

### Module 5: Expectation

- Slides: [Module 5](Probability/2026/Slides/Module_5.pdf); [Module 5 Annotated](Probability/2026/Slides/Module_5_annotated.pdf) 

- Problem Set Solutions: [Module 5 Solution](Probability/2026/Solutions/Module_5_Solutions.pdf) 

- Recordings: [link](https://play.library.utoronto.ca/watch/7a9e6d8b808c38df6cb7ce8187b8e0b2)

### Module 6: Inequalities

- Slides: [Module 6](Probability/2026/Slides/Module_6.pdf);  
[Module 6 Annotated](Probability/2026/Slides/Module_6_annotated.pdf)

- Problem Set Solutions: [Module 6 Solution](Probability/2026/Solutions/Module_6_Solutions.pdf)

- Recordings: [link](https://play.library.utoronto.ca/watch/75d3530455bccc56d0cb86822c2e69fd)

### Module 7: Stochastic Convergence


- Slides: [Module 7](Probability/2026/Slides/Module_7.pdf); 
 [Module 7 Annotated](Probability/2026/Slides/Module_7_annotated.pdf) 

- Problem Set Solutions: [Module 7 Solution](Probability/2026/Solutions/Module_7_Solutions.pdf) 

- Recordings: [link](https://play.library.utoronto.ca/watch/4d79ad26f84b123bde13f1cff3547ded)

### Module 8: Limit Theorems

- Slides: [Module 8](Probability/2026/Slides/Module_8.pdf); [Module 8 Annotated](Probability/2026/Slides/Module_8_annotated.pdf) 

<!-- <!-- - Problem Set Solutions: [Module 8 Solution](Probability/2026/Solutions/Module_8_Solutions.pdf)  -->

<!-- - Recordings: [link](https://play.library.utoronto.ca/watch/c722834abacf9138703c523722c3d2ec) -->

### Module 9 - 10: Counterexamples

<!-- - Slides: [Module 9- 10](Probability/2026/Slides/Module_9.pdf);  -->
<!--  [Module 9 Annotated](Probability/2026/Slides/Module_9_annotated.pdf)  -->

<!--  - Recordings (Module 9): [link](https://play.library.utoronto.ca/watch/f901434b6fded8a4a8d899d167685661) -->

<!--  - Recordings (Module 10):[link](https://play.library.utoronto.ca/watch/0e151f10481d44f74d443cbd4414ac76) -->