---
title: " "
output: 
  html_document:
   toc: true
   toc_float: true
   theme: yeti
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
knitr::opts_chunk$set(warning = F, message = F)
```
<br>

# <span class="glyphicon glyphicon-calendar" aria-hidden="false"></span> Course Schedule
Below is our course schedule, which may change as the course progresses. The morning session will run from 10:00 am-12:00 pm and the afternoon session will run from 1:30-3:30 pm (all times EDT/Toronto time).

Some days will include a lunchtime guest speaker from DoSS or the university from 12:15 - 1:15 pm.  A list of guest speakers will be added closer to the start of the program.

```{r, echo=FALSE}
library(tidyverse)
library(kableExtra)
options(knitr.kable.NA = '')
my_backgrounds <- colorRampPalette(c("white", "gray"))(5)
k <- 9
row_nums <-sort(c(seq(1,31,4), seq(2,31,4)))
jsc270courseschedule <- read_csv("schedule.csv")
knitr::kable(jsc270courseschedule[1:31,]) %>%  
  kable_styling(full_width = T, position = "float_left")   %>%   
  row_spec(row_nums ,background = my_backgrounds[2]) 
```

<br>



